### ISSUE TITLE
Change "preUpdate" to "PreUpdate" in Google\GeolocationBundle\Entity\ApiLog

### ISSUE THREAD

**Issue by gentisaliu** [dsyph3r/GoogleGeolocationBundle#11]
Please change "@ORM\preUpdate" to "@ORM\PreUpdate" in line 49 so that the bundle can work correctly in Linux installations.

As of now I get the error
"[Doctrine\Common\Annotations\AnnotationException]
  [Semantical Error] The annotation "@Doctrine\ORM\Mapping\preUpdate" in method Google\GeolocationBundle\Entity\ApiLog::setUpdatedValue() does not exist, or could not be auto-loaded."

in Linux whenever I run any of the doctrine console commands or my Symfony2 application.

See also: http://stackoverflow.com/questions/12735010/doctrine2-haslifecyclecallbacks-semantical-error/12736196#12736196

**Comment by dsyph3r** [comment]
Thanks for details. Would you be able to submit a pull request with this fix? If not, I'll take a look at it later this week.

**Comment by hugomn** [comment]
I've made a pull request to correct this:
https://github.com/dsyph3r/GoogleGeolocationBundle/pull/12

Thanks, dsyph3r!

**Comment by dsyph3r** [comment]
Great, thanks for submitting. PR merged.

**Comment by gentisaliu** [comment]
Thanks for submitting. I apologize, I could only get back today.
