### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by ph-il** [dsyph3r/GoogleGeolocationBundle#2]
Did have some problems to activate the cache.  Can you provide more documentation.  Thanx!

**Comment by dsyph3r** [comment]
I have updated the Readme with more specific information on how to configure the caching layer. See [commit](https://github.com/dsyph3r/GoogleGeolocationBundle/commit/357007c60f310dc86e300a265b5f9853c3c7e5f1) for more details. Let me know if you need more information.

**Comment by ph-il** [comment]
Look good, thanx!
